# Generated by Django 3.1.3 on 2021-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210531_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='coach',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='teams',
            name='president',
            field=models.CharField(blank=True, max_length=100, verbose_name='Президент'),
        ),
        migrations.AddField(
            model_name='teams',
            name='year',
            field=models.IntegerField(blank=True, default=0, verbose_name='Год основания'),
        ),
    ]
