# Generated by Django 3.1.3 on 2021-06-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210604_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='on_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.matches'),
        ),
    ]
