# Generated by Django 3.1.3 on 2021-05-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название матча')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('price', models.CharField(max_length=40, verbose_name='Цена билета')),
                ('numb_tickets', models.IntegerField(verbose_name='Кол-во билетов')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
