# Generated by Django 3.1.3 on 2021-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='slug',
            field=models.SlugField(default='slag', unique=True),
        ),
    ]
