# Generated by Django 3.1.3 on 2021-05-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='off_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на офф сайт'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matches')),
            ],
        ),
    ]
