# Generated by Django 3.1.3 on 2021-06-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210531_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер билета'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Информация о команде'),
        ),
    ]
