# Generated by Django 3.1.3 on 2021-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210601_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='number',
            field=models.CharField(max_length=400, unique=True, verbose_name='Номер билета'),
        ),
    ]
