# Generated by Django 3.1.3 on 2021-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210604_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='id',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='number',
            field=models.CharField(blank=True, max_length=400, primary_key=True, serialize=False, unique=True, verbose_name='Номер билета'),
        ),
    ]
