# Generated by Django 3.1.3 on 2021-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210604_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='match',
            new_name='on_match',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='sector',
        ),
        migrations.AddField(
            model_name='matches',
            name='ticket',
            field=models.CharField(default='', max_length=10, verbose_name='Билеты'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
