# Generated by Django 3.1.3 on 2021-06-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210604_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='on_match',
            new_name='match',
        ),
    ]
