# Generated by Django 3.1.3 on 2021-06-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210604_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.matches'),
        ),
    ]
