# Generated by Django 3.1.3 on 2021-06-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210605_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='total_tickets',
        ),
        migrations.AddField(
            model_name='matches',
            name='numb_tickets',
            field=models.IntegerField(default=0, verbose_name='Кол-во билетов'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='price',
            field=models.CharField(max_length=40, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название матча'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.matches'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='number',
            field=models.CharField(blank=True, max_length=400, primary_key=True, serialize=False, verbose_name='Номер билета'),
        ),
    ]
